version: 2.1

# orbs:
#   coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          name: 'INSTALLING DEPENDENCY'
          command: npm install
      - run:
          name: 'TESTING'
          command: npm run test
      # - coveralls/upload 

workflows:
  test-deploy:
    jobs:
      - build
   
# notify:
#   webhooks:
#     - url: https://coveralls.io/webhook?repo_token=$%7Bprocess.env.COVERALLS_REPO_TOKEN%7D 