version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    steps:
      - checkout
      - run:
          name: 'INSTALLING DEPENDENCY'
          command: npm install
      - run:
          name: 'TESTING'
          command: 'yarn run test'
      - run:
          name: coverage
          command: yarn run coverage

      - coveralls/upload
      - store_artifacts:
          path: test-results

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: test-results

workflows:
  test-deploy:
    jobs:
      - build